name: funder_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  image_picker: ^1.0.7
  flutter_svg: ^2.0.10+1
  get_storage: ^2.1.1	
  smooth_page_indicator: ^1.1.0
  timeline_tile: ^2.0.0
  http: ^1.2.1
  searchfield: ^1.0.1
  lottie: ^3.1.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  intl: ^0.17.0
  iconly: ^1.0.1
  animated_snack_bar: ^0.4.0
  textfield_datepicker: ^0.1.0
  timeago: ^3.3.0
  share_plus: ^10.0.3
  url_launcher: ^6.3.1
  webview_flutter: ^4.8.0


dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/TextField_Icons/
    - assets/socail_media/
    - assets/wallet_assets/
  fonts:
    - family: Lato
      fonts:
        - asset: assets/lato.ttf
    - family: Roboto
      fonts:
        - asset: assets/Roboto.ttf
    - family: Poppins
      fonts:
        - asset: assets/Poppins.ttf
    - family: Poppins-Light
      fonts:
        - asset: assets/Poppins-Light.ttf
    - family: Tajawal-Regular
      fonts:
        - asset: assets/Tajawal-Regular.ttf
        

        

